### PR TITLE
Only warn for unused new

### PR DESCRIPTION
**Pull request by PieterWigboldus**
Also upgrade doc max length to 120

### CODE REVIEW

**Comment by elwinvaneede** [comment]
What is the use case where you might want an unused ‘new’ statement?

**Comment by PieterWigboldus** [comment]
@elwinvaneede 
A class constructors must be invoked with 'new'
So if something is called from the constructor, you need the new.

Also check e.g.
```
new Vue({
  el: '#app',
  data: obj
})
```

**Comment by elwinvaneede** [comment]
Yes but you use it in conjunction with return in a constructor, right? So then it’s not unused and it won’t trigger this rule.

And Vue uses ‘var vm = new Vue’ in most examples, but I guess you then get a unused variable warning or even error?

But a warn is fine by me.

**Comment by johanvanhelden** [comment]
Even a warning seems a bit unwanted to me. A warning means to me you are doing something wrong and should be fixed :thinking:

**Pull request merged**
